version: 2.1
executors:
  builder:
    docker:
      - image: circleci/node:16.13.1

jobs:
  install:
    executor: builder
    steps:
      - checkout
      - run:
          name: 'Install'
          command: npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - ./*
  build:
    executor: builder
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Build'
          command: npm run build
  version:
    executor: builder
    steps:
      - attach_workspace:
          at: .
      - run:
          command: echo "" > old_version && echo "" > new_version
      - run:
          name: 'Version'
          command: npx semantic-release
      - persist_to_workspace:
          root: ./
          paths:
            - old_version
            - new_version
  build-docker:
    executor: builder
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - attach_workspace:
          at: .
      # - run: mkdir -p ~/.ssh
      # - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: 'Build Docker Image'
          command: |
            OLD_VERSION=$(cat old_version)
            NEW_VERSION=$(cat new_version)
            echo "From ${OLD_VERSION} to ${NEW_VERSION}"
            if [[ -z "${NEW_VERSION}" ]]; then
              echo "No new version. Skip deploy."
            else
              # git pull
              echo "Building v${NEW_VERSION}"
              echo "garredow/foxcasts-cloud-api:${NEW_VERSION}-${CIRCLE_BUILD_NUM}"
              echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
              docker build -t garredow/foxcasts-cloud-api:$NEW_VERSION-$CIRCLE_BUILD_NUM .
              docker push garredow/foxcasts-cloud-api:$NEW_VERSION-$CIRCLE_BUILD_NUM
            fi
  deploy:
    executor: builder
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Deploy'
          command: |
            OLD_VERSION=$(cat old_version)
            NEW_VERSION=$(cat new_version)
            echo "From ${OLD_VERSION} to ${NEW_VERSION}"
            if [[ -z "${NEW_VERSION}" ]]; then
              echo "No new version. Skip deploy."
            else
              echo "Deploying v${NEW_VERSION}"
              ssh -oStrictHostKeyChecking=no -v $DO_USER@$DO_IP_ADDRESS "./apps/foxcasts-cloud-api/install.sh garredow/foxcasts-cloud-api:${NEW_VERSION}-${CIRCLE_BUILD_NUM}"
            fi

workflows:
  build-and-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - version:
          context: github-versioning
          requires:
            - build
          filters:
            branches:
              only:
                - cicd
      - build-docker:
          context: docker-hub
          requires:
            - version
          filters:
            branches:
              only:
                - cicd
      - deploy:
          context: digital-ocean-2
          requires:
            - build-docker
          filters:
            branches:
              only:
                - cicd
